In [5]:
import numpy as np

In [12]:
a = np.array([1,2,3])   # jednodimenzioni niz
print(a)
print(a.shape)   # ako u shape fali drugi element kao ovde, onda je to niz a ne matrica
print(type(a))
print(a[0], a[1], a[2])
a[2] = 5
print(a)

[1 2 3]
(3,)
<class 'numpy.ndarray'>
1 2 3
[1 2 5]


In [14]:
# visedimenzioni niz je niz nizova
b = np.array([ [1,2,3], [4,5,6]])
# mozemo indeksirati onako standarno sa [i][j] ali preporuka je da se za numpy nizove koristi
# indeksiranje sa [i, j]. To je zato sto se u pozadini ako imamo [][] pravi temp niz posle prvog []
print( b[0,1])

2


In [22]:
# jedinicna matrica
a = np.eye(4)
print(a)

# niz inicijalizovan nulama (prosledimo dimenzije)
b = np.zeros((2,2))
print(b)

# niz inicijalizovan jedinicama
c = np.ones((2,3))
print(c)

# niz inicijalizovan nekom vrednoscu koju zelimo
d = np.full((3,4), 7)
print(d)

# matrica sa nasumicnim vrednostima, moramo prvo postaviti neki seed
np.random.seed(42)
e = np.random.random((2,2))
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [25]:
# VAZNO:
# recimo da hocemo da napravimo matricu (3x4)
a = np.array( [[1,2,3,4], [5,6,7,8],[9,10,11,12] ])

# mozemo raditi slice-ovanje ndimenzionog niza u numpyju ali ima specificnost
b = a[:2, 1:3]
print(b)

# ALI, kada izmenimo vrednost u toj novoj matrici, izmenice se i polazna matrica
# znaci mi smo samo napravili "pogled"/ referencu na deo polaznog niza
# znaci OBAVEZNO raditi deepcopy!
b[0][0] = 77
print(a)

[[2 3]
 [6 7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
# ako ne navedemo tip, on ce sam biti zakljucen (ovde bi bio int) i to moze uticati na rezultat operacija
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# imamo operacije sa matricama po koordinatama
print(x+y)
print(x-y)
print(x*y)   # OVO JE KOORDINATNO MNOZENJE, A NE MNOZENJE MATRICA
print(x/y)

print(x.dot(y)) # OVO JE PRAVO MNOZENJE MATRICA

v = np.array([9, 10])
w = np.array([11, 12])
print(v.dot(w))         #skalarni proizvod vektora (jednodimenzionih nizova)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
